baseURL = "https://agaura.github.io"
languageCode = "en-us"
title = "Alexander Gaura"
copyright = "TH â†” Ãž" # lol using this for other functionality, maybe want it like this one day: ê§ TH â†” Ãž ê§‚
googleAnalytics = "G-BBWS173BMQ"

# paginate decides the number of the newest posts
# that'll be shown on the home page.
paginate = 6

# theme is the name of the hugo theme you're gonna use,
# `hugo-theme-minima` is put here only for debuging,
# just name it what's under your theme directory.
theme = "minima"

# Author has some of your information to be shown on the home page.
[author]
name = "Alexander Gaura"
#slogon = "ðŸŒ"
description = '''
Welcome to this space! Feel free to look through the following:
'''


[params]
# iam is the beginning words of your self-introduction.
iam = "::"
# The subtitle will be shown after the title of your blog site.
# e.g. "title - subtitle".
subtitle = ""
# Comment decides the comment plugin to be used on your blog site, 
# e.g. disqus, utterances, ovo.
comment = "utterances"
# Timeformat, no matter what format to use, make it the second day of Jan. 2006
timeformat = "Jan 02, 2006"
# switch for turning on/off lights.
switch = ["âšªï¸", "âš«ï¸"]
# default theme. e.g. light, dark, system
defaultTheme = "system"
# If set true, date of posts will be shown in the homepage.
displayDate = true
# If set true, users can select text from your post.
selectable = true
# Custom global font. notice: `globalFontFamily` won't be working
# on texts in some special positions like on titles
globalFontFamily = ""
# If set true, all your posts will use the chosen comment plugin
# except those with a `comment: false` in their front-matter
commentOnAllPosts = false
# toc decides the shape of the toc button. e.g. default, lines, bar
toc = "lines"

recent = ">> Recent Posts"
older = "Older Posts"

# Disqus configuration
[params.disqus]
shortname = "hugo-minima"

# Utterances configuration
# Full doc's at https://utteranc.es
# **notice**: if you're going to use utterances, you must change the 
# `repo` to your own repo address that stores comments on your site
[params.utterances]
repo = "mivinci/hugo-theme-minima"
issueTerm = "pathname"

# **deprecated**
# OvO is a comment plugin written by the author of Minima.
# It is enabled when params.comment is set "ovo". You can
# have a live view on https://ovo.js.org. If you are using 
# disqus or utterance, just ignore this.
[params.ovo]
server = ""
placeholder = ""


# Params.social is an array containing your social network accounts,
# Each has a lowercase name, a svg formatted icon and a url to the 
# webpage of your account. They will be shown at the bottom of every
# page of your blog. 
# Be sure the svgs you use must have both its width and its height
# set 18. If you don't wanna put the svg code in this config file, 
# since they are too long, you can instead save them to the 
# `data/svg.toml` file under the root directory of your blog. 
# in that file, each line must be formatted as `name = '<svg>'`
# where `<svg>` is the svg code.
[[params.social]]
name = "github"  
url = "https://github.com/agaura"
svg = ""
[[params.social]]
name = "instagram"
url = "https://www.instagram.com/arg793/"
svg = '<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24"><path fill = "#bc2a8d" d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z"/></svg>'
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/alexander-gaura-19980514a/"
svg = ""
[[params.social]]
name = "rss"
url = "/index.xml"
svg = '<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24"><path fill = "#ee802f" d="M6.503 20.752c0 1.794-1.456 3.248-3.251 3.248-1.796 0-3.252-1.454-3.252-3.248 0-1.794 1.456-3.248 3.252-3.248 1.795.001 3.251 1.454 3.251 3.248zm-6.503-12.572v4.811c6.05.062 10.96 4.966 11.022 11.009h4.817c-.062-8.71-7.118-15.758-15.839-15.82zm0-3.368c10.58.046 19.152 8.594 19.183 19.188h4.817c-.03-13.231-10.755-23.954-24-24v4.812z"/></svg>'

# If set, titles and links of the topk newest posts extracted from 
# the feeds will be displayed in the home page. Note that the feeds
# providers have to make their 'Access-Control-Allow-Origin' contain
# your domain, otherwise the feeds cannot be fetched.
#[params.friends]
#feeds = ["https://agaura.github.io/categories/projects/index.xml"]
#topk = 3
#title = ">> Projects"
#proxy = "" # reserved


# Menu.main is an array that's used to decide what entries can be shown
# on the navigator of yur blog. You can use a weight to make them ordered.
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Writing"
url = "/categories/writing"
weight = 2
[[menu.main]]
name = "Projects"
url = "/categories/projects"
weight = 3
#[[menu.main]]
#name = "Series"
#url = "/series"
#weight = 3
[[menu.main]]
name = "About"
url = "/about"
weight = 4


# You can classify your posts by setting taxanomies in the front matter
# e.g.
#     categories = ["dev"]
#     series = ["Building an RPC server"]
#     tags = ["hugo", "golang"]
# A little suggestion: one post belongs to one series or one category or multiple tags.
[taxonomies]
category = "categories"
tag = "tags"
series = "series"


# Fields below make sure all the codes in a post are
# highlighted correctly, so better not edit them.
[markup.highlight]
lineNos = true
noClasses = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true